import 'package:hive_ce_flutter/hive_flutter.dart';

import '../../hive_registrar.g.dart';
import '../../features/student/domain/grade_subject_entry.dart';
import '../../features/student/domain/student_grades_settings.dart';
import '../../features/student/domain/student_majors_settings.dart';
import '../../features/student/domain/student_profile.dart';
import '../../features/student/domain/test_entry.dart';
import '../../features/student/domain/university_target.dart';
import 'hive_boxes.dart';

/// Registers every @HiveType adapter and opens every box the app needs,
/// up front, before `runApp()`.
///
/// This is the Day 2 Step 0 fix: planning.md's Day 0 checklist claimed
/// this was already done, but direct inspection of the actual code found
/// `main.dart` never called `Hive.initFlutter()` and registered no
/// adapters at all — see day2-codebase-reference.md's "CRITICAL GAP"
/// note. Call this once from `main()`, before `ProviderScope`/`runApp`,
/// since Student's Profile / My Tests / My Grades all read/write their
/// boxes as soon as their screens build.
///
/// Adapter registration itself is delegated to `Hive.registerAdapters()`,
/// generated by `hive_ce_generator` into `lib/hive_registrar.g.dart` (that
/// file is checked into version control per Hive CE's own convention —
/// it's NOT hand-maintained, don't edit it directly). The generator scans
/// the whole `lib/` tree for `@HiveType`-annotated classes, so a new model
/// added later gets picked up automatically the next time
/// `dart run build_runner build` runs — nobody has to remember to add a
/// line here by hand. This closes off the exact failure mode that created
/// the original Day 0 gap: a step that was "supposed to happen" but
/// silently didn't, because it depended on a human remembering it.
///
/// typeIds are still tracked below for reference even though nothing here
/// assigns them anymore — `hive_ce_generator` reads them straight off each
/// model's `@HiveType(typeId: N)` annotation. Reserved so far:
/// 0 StudentProfile, 1 TestEntry, 2 TestType, 3 TestStatus,
/// 4 GradeSubjectEntry, 5 GradeSubjectGroup, 6 ParentGuardianEntry,
/// 7 GradeTrack, 8 StudentGradesSettings, 9 MajorEntry,
/// 10 StudentMajorsSettings, 11 UniversityTarget. Next free id is **12**.
Future<void> initHive() async {
  await Hive.initFlutter();
  Hive.registerAdapters();

  await Future.wait([
    Hive.openBox<StudentProfile>(HiveBoxes.studentProfile),
    Hive.openBox<TestEntry>(HiveBoxes.studentTests),
    Hive.openBox<GradeSubjectEntry>(HiveBoxes.studentGrades),
    Hive.openBox<StudentGradesSettings>(HiveBoxes.studentGradesSettings),
    Hive.openBox<StudentMajorsSettings>(HiveBoxes.studentMajors),
    Hive.openBox<UniversityTarget>(HiveBoxes.studentUniversityTargets),
  ]);
}