// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:runata_pathway/features/student/domain/grade_subject_entry.dart';
import 'package:runata_pathway/features/student/domain/major_entry.dart';
import 'package:runata_pathway/features/student/domain/parent_guardian_entry.dart';
import 'package:runata_pathway/features/student/domain/student_grades_settings.dart';
import 'package:runata_pathway/features/student/domain/student_majors_settings.dart';
import 'package:runata_pathway/features/student/domain/student_profile.dart';
import 'package:runata_pathway/features/student/domain/test_entry.dart';
import 'package:runata_pathway/features/student/domain/university_target.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GradeSubjectEntryAdapter());
    registerAdapter(GradeSubjectGroupAdapter());
    registerAdapter(GradeTrackAdapter());
    registerAdapter(MajorEntryAdapter());
    registerAdapter(ParentGuardianEntryAdapter());
    registerAdapter(StudentGradesSettingsAdapter());
    registerAdapter(StudentMajorsSettingsAdapter());
    registerAdapter(StudentProfileAdapter());
    registerAdapter(TestEntryAdapter());
    registerAdapter(TestStatusAdapter());
    registerAdapter(TestTypeAdapter());
    registerAdapter(UniversityTargetAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GradeSubjectEntryAdapter());
    registerAdapter(GradeSubjectGroupAdapter());
    registerAdapter(GradeTrackAdapter());
    registerAdapter(MajorEntryAdapter());
    registerAdapter(ParentGuardianEntryAdapter());
    registerAdapter(StudentGradesSettingsAdapter());
    registerAdapter(StudentMajorsSettingsAdapter());
    registerAdapter(StudentProfileAdapter());
    registerAdapter(TestEntryAdapter());
    registerAdapter(TestStatusAdapter());
    registerAdapter(TestTypeAdapter());
    registerAdapter(UniversityTargetAdapter());
  }
}
