// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:runata_pathway/features/student/domain/grade_subject_entry.dart';
import 'package:runata_pathway/features/student/domain/student_profile.dart';
import 'package:runata_pathway/features/student/domain/test_entry.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GradeSubjectEntryAdapter());
    registerAdapter(GradeSubjectGroupAdapter());
    registerAdapter(StudentProfileAdapter());
    registerAdapter(TestEntryAdapter());
    registerAdapter(TestStatusAdapter());
    registerAdapter(TestTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GradeSubjectEntryAdapter());
    registerAdapter(GradeSubjectGroupAdapter());
    registerAdapter(StudentProfileAdapter());
    registerAdapter(TestEntryAdapter());
    registerAdapter(TestStatusAdapter());
    registerAdapter(TestTypeAdapter());
  }
}
